# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Produce verbose output by default.
VERBOSE = 1

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/nameblank00/Desktop/Projects/2_NJL_Diquark

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/nameblank00/Desktop/Projects/2_NJL_Diquark

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nameblank00/Desktop/Projects/2_NJL_Diquark/CMakeFiles /home/nameblank00/Desktop/Projects/2_NJL_Diquark//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nameblank00/Desktop/Projects/2_NJL_Diquark/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named libTMQGP

# Build rule for target.
libTMQGP: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libTMQGP
.PHONY : libTMQGP

# fast build rule for target.
libTMQGP/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libTMQGP.dir/build.make CMakeFiles/libTMQGP.dir/build
.PHONY : libTMQGP/fast

#=============================================================================
# Target rules for targets named TMQGP

# Build rule for target.
TMQGP: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TMQGP
.PHONY : TMQGP

# fast build rule for target.
TMQGP/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TMQGP.dir/build.make CMakeFiles/TMQGP.dir/build
.PHONY : TMQGP/fast

TMQGP/IntGSL.o: TMQGP/IntGSL.cpp.o
.PHONY : TMQGP/IntGSL.o

# target to build an object file
TMQGP/IntGSL.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libTMQGP.dir/build.make CMakeFiles/libTMQGP.dir/TMQGP/IntGSL.cpp.o
.PHONY : TMQGP/IntGSL.cpp.o

TMQGP/IntGSL.i: TMQGP/IntGSL.cpp.i
.PHONY : TMQGP/IntGSL.i

# target to preprocess a source file
TMQGP/IntGSL.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libTMQGP.dir/build.make CMakeFiles/libTMQGP.dir/TMQGP/IntGSL.cpp.i
.PHONY : TMQGP/IntGSL.cpp.i

TMQGP/IntGSL.s: TMQGP/IntGSL.cpp.s
.PHONY : TMQGP/IntGSL.s

# target to generate assembly for a file
TMQGP/IntGSL.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libTMQGP.dir/build.make CMakeFiles/libTMQGP.dir/TMQGP/IntGSL.cpp.s
.PHONY : TMQGP/IntGSL.cpp.s

TMQGP/Interpolator.o: TMQGP/Interpolator.cpp.o
.PHONY : TMQGP/Interpolator.o

# target to build an object file
TMQGP/Interpolator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libTMQGP.dir/build.make CMakeFiles/libTMQGP.dir/TMQGP/Interpolator.cpp.o
.PHONY : TMQGP/Interpolator.cpp.o

TMQGP/Interpolator.i: TMQGP/Interpolator.cpp.i
.PHONY : TMQGP/Interpolator.i

# target to preprocess a source file
TMQGP/Interpolator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libTMQGP.dir/build.make CMakeFiles/libTMQGP.dir/TMQGP/Interpolator.cpp.i
.PHONY : TMQGP/Interpolator.cpp.i

TMQGP/Interpolator.s: TMQGP/Interpolator.cpp.s
.PHONY : TMQGP/Interpolator.s

# target to generate assembly for a file
TMQGP/Interpolator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libTMQGP.dir/build.make CMakeFiles/libTMQGP.dir/TMQGP/Interpolator.cpp.s
.PHONY : TMQGP/Interpolator.cpp.s

TMQGP/Meson_PhaseShift_and_Pressure.o: TMQGP/Meson_PhaseShift_and_Pressure.cpp.o
.PHONY : TMQGP/Meson_PhaseShift_and_Pressure.o

# target to build an object file
TMQGP/Meson_PhaseShift_and_Pressure.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libTMQGP.dir/build.make CMakeFiles/libTMQGP.dir/TMQGP/Meson_PhaseShift_and_Pressure.cpp.o
.PHONY : TMQGP/Meson_PhaseShift_and_Pressure.cpp.o

TMQGP/Meson_PhaseShift_and_Pressure.i: TMQGP/Meson_PhaseShift_and_Pressure.cpp.i
.PHONY : TMQGP/Meson_PhaseShift_and_Pressure.i

# target to preprocess a source file
TMQGP/Meson_PhaseShift_and_Pressure.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libTMQGP.dir/build.make CMakeFiles/libTMQGP.dir/TMQGP/Meson_PhaseShift_and_Pressure.cpp.i
.PHONY : TMQGP/Meson_PhaseShift_and_Pressure.cpp.i

TMQGP/Meson_PhaseShift_and_Pressure.s: TMQGP/Meson_PhaseShift_and_Pressure.cpp.s
.PHONY : TMQGP/Meson_PhaseShift_and_Pressure.s

# target to generate assembly for a file
TMQGP/Meson_PhaseShift_and_Pressure.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libTMQGP.dir/build.make CMakeFiles/libTMQGP.dir/TMQGP/Meson_PhaseShift_and_Pressure.cpp.s
.PHONY : TMQGP/Meson_PhaseShift_and_Pressure.cpp.s

TMQGP/Meson_Polarization.o: TMQGP/Meson_Polarization.cpp.o
.PHONY : TMQGP/Meson_Polarization.o

# target to build an object file
TMQGP/Meson_Polarization.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libTMQGP.dir/build.make CMakeFiles/libTMQGP.dir/TMQGP/Meson_Polarization.cpp.o
.PHONY : TMQGP/Meson_Polarization.cpp.o

TMQGP/Meson_Polarization.i: TMQGP/Meson_Polarization.cpp.i
.PHONY : TMQGP/Meson_Polarization.i

# target to preprocess a source file
TMQGP/Meson_Polarization.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libTMQGP.dir/build.make CMakeFiles/libTMQGP.dir/TMQGP/Meson_Polarization.cpp.i
.PHONY : TMQGP/Meson_Polarization.cpp.i

TMQGP/Meson_Polarization.s: TMQGP/Meson_Polarization.cpp.s
.PHONY : TMQGP/Meson_Polarization.s

# target to generate assembly for a file
TMQGP/Meson_Polarization.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libTMQGP.dir/build.make CMakeFiles/libTMQGP.dir/TMQGP/Meson_Polarization.cpp.s
.PHONY : TMQGP/Meson_Polarization.cpp.s

TMQGP/TMInterpolator_P.o: TMQGP/TMInterpolator_P.cpp.o
.PHONY : TMQGP/TMInterpolator_P.o

# target to build an object file
TMQGP/TMInterpolator_P.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libTMQGP.dir/build.make CMakeFiles/libTMQGP.dir/TMQGP/TMInterpolator_P.cpp.o
.PHONY : TMQGP/TMInterpolator_P.cpp.o

TMQGP/TMInterpolator_P.i: TMQGP/TMInterpolator_P.cpp.i
.PHONY : TMQGP/TMInterpolator_P.i

# target to preprocess a source file
TMQGP/TMInterpolator_P.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libTMQGP.dir/build.make CMakeFiles/libTMQGP.dir/TMQGP/TMInterpolator_P.cpp.i
.PHONY : TMQGP/TMInterpolator_P.cpp.i

TMQGP/TMInterpolator_P.s: TMQGP/TMInterpolator_P.cpp.s
.PHONY : TMQGP/TMInterpolator_P.s

# target to generate assembly for a file
TMQGP/TMInterpolator_P.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libTMQGP.dir/build.make CMakeFiles/libTMQGP.dir/TMQGP/TMInterpolator_P.cpp.s
.PHONY : TMQGP/TMInterpolator_P.cpp.s

TMQGP/test.o: TMQGP/test.cpp.o
.PHONY : TMQGP/test.o

# target to build an object file
TMQGP/test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libTMQGP.dir/build.make CMakeFiles/libTMQGP.dir/TMQGP/test.cpp.o
.PHONY : TMQGP/test.cpp.o

TMQGP/test.i: TMQGP/test.cpp.i
.PHONY : TMQGP/test.i

# target to preprocess a source file
TMQGP/test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libTMQGP.dir/build.make CMakeFiles/libTMQGP.dir/TMQGP/test.cpp.i
.PHONY : TMQGP/test.cpp.i

TMQGP/test.s: TMQGP/test.cpp.s
.PHONY : TMQGP/test.s

# target to generate assembly for a file
TMQGP/test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libTMQGP.dir/build.make CMakeFiles/libTMQGP.dir/TMQGP/test.cpp.s
.PHONY : TMQGP/test.cpp.s

wrap.o: wrap.cpp.o
.PHONY : wrap.o

# target to build an object file
wrap.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TMQGP.dir/build.make CMakeFiles/TMQGP.dir/wrap.cpp.o
.PHONY : wrap.cpp.o

wrap.i: wrap.cpp.i
.PHONY : wrap.i

# target to preprocess a source file
wrap.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TMQGP.dir/build.make CMakeFiles/TMQGP.dir/wrap.cpp.i
.PHONY : wrap.cpp.i

wrap.s: wrap.cpp.s
.PHONY : wrap.s

# target to generate assembly for a file
wrap.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TMQGP.dir/build.make CMakeFiles/TMQGP.dir/wrap.cpp.s
.PHONY : wrap.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... TMQGP"
	@echo "... libTMQGP"
	@echo "... TMQGP/IntGSL.o"
	@echo "... TMQGP/IntGSL.i"
	@echo "... TMQGP/IntGSL.s"
	@echo "... TMQGP/Interpolator.o"
	@echo "... TMQGP/Interpolator.i"
	@echo "... TMQGP/Interpolator.s"
	@echo "... TMQGP/Meson_PhaseShift_and_Pressure.o"
	@echo "... TMQGP/Meson_PhaseShift_and_Pressure.i"
	@echo "... TMQGP/Meson_PhaseShift_and_Pressure.s"
	@echo "... TMQGP/Meson_Polarization.o"
	@echo "... TMQGP/Meson_Polarization.i"
	@echo "... TMQGP/Meson_Polarization.s"
	@echo "... TMQGP/TMInterpolator_P.o"
	@echo "... TMQGP/TMInterpolator_P.i"
	@echo "... TMQGP/TMInterpolator_P.s"
	@echo "... TMQGP/test.o"
	@echo "... TMQGP/test.i"
	@echo "... TMQGP/test.s"
	@echo "... wrap.o"
	@echo "... wrap.i"
	@echo "... wrap.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

